studentCSVCRUD frontend
ucsb-cs156-f20/proj-mapache-search pull request #78
Opened 2020-12-10 05:50 UTC by kokinarimoto

This pull request contains the frontend of the studentCSVCRUD story. There is also some backend code added to this; however, the full code will be for the backend of the studentCSVCRUD story.

We have rated this a 4 due to the various components needed to implement a fully functional CRUD for students and to be able to implement adequate test coverage for the different cases.

2020-12-12 02:39 UTC, gracsoo approved these changes
everything looks good :)

2020-12-12 04:33 UTC, mara-downing requested changes
Preliminary concern: I'm uploading a file that just looks like:
`
mail,team
student1@email,team1
student2@email,team2
`
and it doesn't seem to upload, the error in the console looks like:
![Screenshot from 2020-12-11 20-28-38](https://user-images.githubusercontent.com/72156992/101975259-f9da7c00-3bef-11eb-8078-fe1915b02d40.png)

Let me know if I'm doing something wrong with the input file, otherwise this would be an error to take a look into.

2020-12-12 08:59 UTC, phtcon requested changes
Some commented out code to delete

2020-12-12 08:59 UTC, phtcon commented on javascript/src/main/utils/fetch.js
> +    // throw new Error("HTTP Error " + json.status + ": " + json.message);
The usual practice is to delete commented out code before doing a PR.

Could we delete these lines?

2020-12-12 08:59 UTC, phtcon commented on javascript/src/test/pages/Students/EditStudent.test.js
> +  // test("Renders spinner with no existing student", () => {
Could we delete these commented out lines?

2020-12-12 08:59 UTC, phtcon commented on javascript/src/test/pages/Students/EditStudent.test.js
> +    // expect(addToast).toHaveBeenCalledTimes(1);
Could we delete these commented out lines?

2020-12-12 08:59 UTC, phtcon commented on javascript/src/test/pages/Students/NewStudent.test.js
> +// }));
Delete commented out lines

2020-12-12 08:59 UTC, phtcon commented on javascript/src/test/pages/Students/StudentCSVButton.test.js
> +    //   });
delete commented out lines

2020-12-12 08:59 UTC, phtcon commented on javascript/src/test/pages/Students/Students.test.js
> +    // });
You guessed it

2020-12-12 08:59 UTC, phtcon commented on javascript/src/test/pages/Students/Students.test.js
> +  //     // If you want it to work, do nothing
You know what to do

2020-12-13 06:01 UTC, phtcon commented
Closed because PR #91 has the code from the branch that the team decided to go forward with

2020-12-13 06:01 UTC, closed without merging